### PR TITLE
Add initial documentation of response policy

### PR DESCRIPTION
**Pull request by alexcrichton**
This is intended to fill out a skeleton of some words to record about
our security response policy from the perspective of the security team.
This isn't trying to change our security policy, just document what we
have so far!

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @rust-lang/security, y'all are likely interested in this!

**Comment by emilyalbini** [comment]
So, the text mostly looks good. Some things I'd love to see changed:

* Move the text away from the readme into a separate file so we can have more documents and such.
* In [the security policy](https://www.rust-lang.org/policies/security#security-receiving) we mentioned we'd post the vulnerabilities to the linux distros private disclosure ML, but we didn't do that last time. That should be mentioned ([along with the instructions](https://oss-security.openwall.org/wiki/mailing-lists/distros#list-policy-and-instructions-for-reporters)). They mentioned they only want medium or high priority vulns reported there, so that should also be mentioned.
* Reporting to the linux distros private disclosure ML requires posting to the [public one once the vuln is public](https://oss-security.openwall.org/wiki/mailing-lists/oss-security). There should be a mention of that in the checklist and possibly in the security policy as well.

**Comment by alexcrichton** [comment]
Do you have a particular organization in mind? Note that this is intended to be a relatively lightweight PR and such, we are free to all push to it and the repo and everything. In terms of emailing distros I'm not personally too familiar with how to do that since I've never done it, would you be ok writing up some info?

**Comment by emilyalbini** [comment]
Ok, merging this, I'll move files on master and then open a PR about mailing lists.

**Comment by emilyalbini** [comment]
Ok the commit was smaller enough I just pushed it to master.

https://github.com/rust-lang/security-team/commit/8a278a4a43392a276f64ac6e29ea4063848a82be

**Pull request merged**
